### ISSUE TITLE
What are these values ?

### ISSUE THREAD

**Issue by AgostinoA** [Fortiphyd/GRFICSv2#15]
Hello,
inside at process simulation, what are these values ?

Inside at Unity 3D
A: 47%
B: 1%
C: 52%

Simulation in C++
A_in_purge
B_in_purge
C_in_purge

ScadaBR
AComp
BComp
CComp

**Comment by djformby** [comment]
They are all the same measurements of the composition of the gas coming out of the purge. What percentage of the gas is chemical A, B, or C

**Comment by AgostinoA** [comment]
> They are all the same measurements of the composition of the gas coming out of the purge. What percentage of the gas is chemical A, B, or C

Forgive me, but what reaction does the reactor deal with: reagent(?) + reagent(?) => product(?) + purge(?). You honestly don't understand.
The composition like that makes no sense... If you don't have a specific reaction.

**Comment by djformby** [comment]
Please read the simulation section of the paper linked in the beginning of the overview of this repo, where we explain that it is using the Simplified Tennessee Eastman Challenge Process. If you then read the references in that paper you will find that the original simulation was created by professors in chemical engineering as a challenging chemical reaction to test different control algorithms on.

The reaction is: chemical A + chemical B => desired liquid product chemical D + undesired chemical C byproduct in gas form

The reaction is realistically not completely efficient and there is leftover chemical A and chemical B in gas form that escapes out the purge valve with the chemical C byproduct
