### ISSUE TITLE
GRFICS info questions - host-only adapters and documentation

### ISSUE THREAD

**Issue by dan00bielb** [Fortiphyd/GRFICSv2#4]
Hi,
first of all thanks for all your work and effort you're putting in such project, it is really a good resource for learning and practicing on ICS. i have only a few questions that i hope you can answer:
- is it possible to change the networking architecture of the environment or it is constrained to the specified host-only network adapters?
- are there more resourse/documentation on how to use and configure the framework besides the provided video tutorials? Or maybe also some already implemented framework use case? 

Thanks,

**Comment by djformby** [comment]
Thanks for the feedback.

- You can modify the architecture, but you would have to understand VirtualBox networking and Linux networking configuration to set it up the way you wanted. We do not provide any resources for this.

- The only documentation for use cases are here in Github and the video tutorials. We have implemented the framework in our paid offering (https://fortiphyd.talentlms.com) and are developing curriculum using the environment
