### ISSUE TITLE
Simulation VM (ChemicalPlant) network issue

### ISSUE THREAD

**Issue by normaliok** [Fortiphyd/GRFICSv2#8]
I've imported VM with NAT interface selected as noticed in description. But I have only loopback interface with no Internet connetction to download all needful updates as mentioned in instruction. I tried to change /etc/network/interface but with no success

**Comment by Cloufish** [comment]
I don't know If previously  they instructed use of NAT Network, but now It's only Host-Only Networking

But I also had issues with Networking on Workstation - a restart of the machine helped to initialize newly created Host-Only Networks

**Comment by muddydev** [comment]
I also had problems with the workstation. 

It appeared to be something to do with the DHCP address being totally wrong. 

I manually edited the interface in the GUI and disabled DHCP client adding in a static IP of 192.168.95.5/24 with a gwaddr of 92.168.95.1. This fixed my problem
